// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    Avatar: typeof import('./src/components/shared/Avatar.vue')['default']
    PrimaryButton: typeof import('./src/components/shared/PrimaryButton.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
    SettingsWeight: typeof import('./src/components/Settings/SettingsWeight.vue')['default']
    Version: typeof import('./src/components/Version.vue')['default']
    WeightBars: typeof import('./src/components/Weight/WeightBars.vue')['default']
    WeightHeatmap: typeof import('./src/components/Weight/WeightHeatmap.vue')['default']
    WeightMonthYear: typeof import('./src/components/Weight/WeightMonthYear.vue')['default']
  }
}
